import { HEADER_ITEM_TYPES } from '@bit/scalez.savvy-ui.header';
import { APP_HEADER_ITEM_TYPES } from 'App/components/AppHeader/AppHeader';

export * from './journey';
export * from './rulesExperience';
export * from './closet';
export * from './chargebee';
export * from './stylist';
export * from './outfit';
export * from './task';
export * from './user';
export * from './media';
export * from './thread';

export enum STANDALONE_STATE_NAMES {
  /* Auth */
  WELCOME_PAGE = 'WELCOME_PAGE',

  /* Navbar pages */
  HOMEPAGE_STATE = 'HOMEPAGE_STATE',
  OUTFIT_FEED_STATE = 'OUTFIT_FEED_STATE',
  CLOSET_STATE = 'CLOSET_STATE',
  INBOX_STATE = 'INBOX_STATE',

  /* Homepage stylist pages */
  CHAT_WITH_STYLIST_STATE = 'CHAT_WITH_STYLIST_STATE',
  HOMEPAGE_STYLIST_OVERVIEW_STATE = 'HOMEPAGE_STYLIST_OVERVIEW_STATE',

  /* Journey pages */
  USER_PROFILE_STATE = 'USER_PROFILE_STATE',

  /* Journey pages */
  CHAPTER_TIMELINE_STATE = 'CHAPTER_TIMELINE_STATE',

  /* Onboarding flow steps */
  ONBOARDING_PHONE_NUMBER_FORM_STATE = 'ONBOARDING_PHONE_NUMBER_FORM_STATE',
  ONBOARDING_CREATE_PROFILE_FORM_STATE = 'ONBOARDING_CREATE_PROFILE_FORM_STATE',
  ONBOARDING_HOW_IT_WORKS_STATE = 'ONBOARDING_HOW_IT_WORKS_STATE',
  ONBOARDING_STYLIST_MATCHING_STATE = 'ONBOARDING_STYLIST_MATCHING_STATE',
  ONBOARDING_STYLIST_LIST_STATE = 'ONBOARDING_STYLIST_LIST_STATE',
  ONBOARDING_STYLIST_OVERVIEW_STATE = 'ONBOARDING_STYLIST_OVERVIEW_STATE',

  /* TaskRouting flow steps */
  TASK_ROUTING_STEP_STATE = 'TASK_ROUTING_STEP_STATE',
  TASK_ROUTING_CATEGORIES_STATE = 'TASK_ROUTING_CATEGORIES_STATE',
  TASK_ROUTING_OVERVIEW_STATE = 'TASK_ROUTING_OVERVIEW_STATE',

  /* MyStyleUps pages */
  THREADS_LIST_STATE = 'THREADS_LIST_STATE',
  THREAD_EVENTS_LIST_STATE = 'THREAD_EVENTS_LIST_STATE',

  /* TaslResult pages */
  TASK_RESULT_STATE = 'TASK_RESULT_STATE',
  TASK_RESULT_RATE_STATE = 'TASK_RESULT_RATE_STATE',
  STYLIST_REPLACEMENT_STATE = 'STYLIST_REPLACEMENT_STATE',
  TASK_SUGGESTIONS_STATE = 'TASK_SUGGESTIONS_STATE',

  /* Task flow steps */
  TASK_OVERVIEW_STATE = 'TASK_OVERVIEW_STATE',
  STYLIST_MATCHING_STATE = 'STYLIST_MATCHING_STATE',
  STYLIST_LIST_STATE = 'STYLIST_LIST_STATE',
  STYLIST_OVERVIEW_STATE = 'STYLIST_OVERVIEW_STATE',
  TASK_AWAIT_STATE = 'TASK_AWAIT_STATE',

  /* Chat pages */
  TASK_CHAT_STATE = 'TASK_CHAT_STATE',
  FORM_CHAT_STATE = 'FORM_CHAT_STATE',

  /* Payment flow steps */
  TRIAL_STATE = 'TRIAL_STATE',
  PRE_PAYMENT_STATE = 'PRE_PAYMENT_STATE',
  PAYMENT_PLAN_STATE = 'PAYMENT_PLAN_STATE',
  PAYMENT_STATE = 'PAYMENT_STATE',
  PAYMENT_SUCCESS_STATE = 'PAYMENT_SUCCESS_STATE',

  /* Other */
  OUTFIT_MATCHING_STATE = 'OUTFIT_MATCHING_STATE',
  OUTFIT_SHARE_STATE = 'OUTFIT_SHARE_STATE',
  CREATE_PROFILE_STATE = 'CREATE_PROFILE_STATE',
  HOW_IT_WORKS_STATE = 'HOW_IT_WORKS_STATE',
  WL_STYLIST_STATE = 'WL_STYLIST_STATE',
  AUTORIZED_STATE = 'AUTORIZED_STATE',
  FREE_RULES_EXPERIENCE_STATE = 'FREE_RULES_EXPERIENCE_STATE',
  APP_DOWNLOAD_STATE = 'APP_DOWNLOAD_STATE',
  PHONE_NUMBER_FORM_STATE = 'PHONE_NUMBER_FORM_STATE'
}

export interface StepData {
  headerConfig: {
    type: HEADER_ITEM_TYPES | APP_HEADER_ITEM_TYPES;
    props?: any;
  }[];
  renderNavbar: boolean;
  renderIntercom: boolean;
  stateName: STANDALONE_STATE_NAMES;
  defaultBack: string;
}
